### ISSUE TITLE
UEP/EURECOM getting 5 star enrichment data out of present CH sources

### ISSUE THREAD

**Issue by lyndonnixon** [linkedtv/wp2#10]
"we may need that there is additional metadata extraction over the key cultural heritage content sources such as Europeana (but also other sites which appear to hide useful knowledge about artworks within unstructured HTML) so that we are able to make more structured queries such as "what are similar art objects along this facet"

**Comment by rtroncy** [comment]
This has been largely dealt with by the editor tool which enables to edit information cards
