### ISSUE TITLE
RBBs SRT files may be stripping out special characters

### ISSUE THREAD

**Issue by lyndonnixon** [linkedtv/wp2#12]
e.g. http://api.linkedtv.eu/data/RBB/srt/BERLIN-2013-04-04-21-45-53-04042145.srt

187
00:11:02,600 --> 00:11:04,600
Auer Steinen nichts.

(should be "Außer")

**Comment by rtroncy** [comment]
curl -u admin:linkedtv -I http://api.linkedtv.eu/data/RBB/srt/BERLIN-2013-04-04-21-45-53-04042145.srt returns:

HTTP/1.1 200 OK
Date: Tue, 22 Jul 2014 15:21:17 GMT
Server: Apache/2.2.15 (CentOS)
Last-Modified: Fri, 09 Aug 2013 14:39:02 GMT
ETag: "921a85-9b2d-4e384bc66fb78"
Accept-Ranges: bytes
Content-Length: 39725
Connection: close
Content-Type: text/plain; charset=UTF-8

So it does return a UTF-8 encoding. It seems that the ß character was removed before, perhaps in the middle of the stl to srt conversion !

@jthomsen Can you look into this issue?

**Comment by jthomsen** [comment]
we checked it, and yes there was a bug in the conversion script; now resolved (but we won't reprocess past STL files unless there is a real necessity)

**Comment by rtroncy** [comment]
Well, there is a necessity, since some German characters have been removed in the file submitted to NERD, so not all potential entities have been found which negatively impact the annotations and enrichments evaluations !

**Comment by jthomsen** [comment]
mmh, well, yes, but this would then make sense only if we also would re-tv2rdf and re-store it in the repository. However, this again would require a complete flush beforehand and complete re-insert. Not talking about the time needed to do this, the potential harm of this process would be currently much bigger than the unquestioned benefit of having correctly recognized also these entities; for the current rbb IFA video however, we took the correct version.

**Comment by rtroncy** [comment]
I would hope that this process is completely automatized from now on, and if it is not yet, why aren't you automatizing it? Flushing is one command and TV2RDF calls will just take less than 1 min to be executed. I don't really understand the time issue.

Is there a way to quickly know from the platform dashboard how many media resources have been processed? Ideally, there should also be a counter corresponding to the number of chapters and entities stored.

**Comment by jthomsen** [comment]
actually, no, not  currently; but these are definitively worthful features; I'll create corresponding github issues to track them

**Comment by rtroncy** [comment]
Closing this  bug since it is now handled at https://github.com/linkedtv/platform/issues/34 and https://github.com/linkedtv/platform/issues/35

**Comment by lyndonnixon** [comment]
Opening this again as Nico reports that 'z' is disappearing from RBB transcripts. (email 7 Aug 1441)

**Comment by rtroncy** [comment]
@jthomsen needs to check if the stl file is a well-formed text and if the transformed srt file is a well-formed text (i.e. without 'z' character disappearing or German characters being stripped out)
