### ISSUE TITLE
Harmonizing the source names coming from UEP unstructured search module

### ISSUE THREAD

**Issue by rtroncy** [linkedtv/wp2#14]
Take this simple query to the MediaCollector: http://linkedtv.eurecom.fr/api/mediacollector/search/SV/spiegel

As you can see, results come from 12 different source: Europeana, YouTube, WikiMediaCommons, and then 9 sources crawled by the UEP unstructured search module.

Those sources do NOT have a normalized names, some being even malformed URI. This has triggered a bug in TVEnricher that creates new URI for each enrichment source. UEP should harmonize those source names since there are meant to be displayable in a client (Player, Editor Tool, etc.)

**Comment by kliegr** [comment]
Thanks for reporting, we are looking into this. The problem seems to be  a bug in the irapi layer of UEP Unstructured Search.

**Comment by kliegr** [comment]
This is fixed in the new release, the preview (for the spiegel query) is at http://ir-dev.lmcloud.vse.cz/irapi/media-server2/?q=%22spiegel%22&media_type=image

**Comment by rtroncy** [comment]
Great! When will the new release be deployed so that those changes are cascaded to MediaCollector/TVEnricher?

Can we also have a discussion on what should be the correct labels for the various enrichment sources?

**Comment by kliegr** [comment]
> Can we also have a discussion on what should be the correct labels for the various enrichment sources?
> Currently, we use the authority name from the white list (e.g. www.worldcat.org).

**Comment by rtroncy** [comment]
There is a discrepancy: for social media sources, we use a human friend label (e.g. Flickr, Instagram, Facebook) while for whited list sources, a url (without protocol) is used

**Comment by rtroncy** [comment]
@kliegr Will this issue also been fixed in the new release of IRAPI planned for 25/08/2014?

**Comment by rtroncy** [comment]
More details in [Michiel's email](https://lists.iais.fraunhofer.de/sympa/arc/linkedtv-wp2/2014-10/msg00004.html)

**Comment by rtroncy** [comment]
Michiel said there is not strong requirement concerning this, www. domain names have been already removed so no further action needed by now.
