### ISSUE TITLE
TVEnricher: enhance response format to feed ET/Player enrichment display

### ISSUE THREAD

**Issue by lyndonnixon** [linkedtv/wp2#23]
@kliegr reported 18 August: "For webpages, we store both the meta title and description tags separately in the index, so it is not a problem for us to serialize them to the IRAPI response (if they are available in the page source code). Currently, the format does not have a suitable field, so it is a matter on agreeing on extension of the specification."

Propose that the micropost field contains TITLE and DESCRIPTION fields (are html and plainText needed for anything outside of the WP2 workflow itself?)

**Comment by lyndonnixon** [comment]
@jluisred what is the ETA for this update?

**Comment by rtroncy** [comment]
This can hardly be before post St Gallen meeting due to already many issues resolving commitments for this week

**Comment by lyndonnixon** [comment]
can i ask again about the status - "that the micropost field contains TITLE and DESCRIPTION fields"
just to add the email confirmation of the related matter - inclusion of a DIMENSION parameter - is ETA'd for before the review (so by end of November)

**Comment by rtroncy** [comment]
@lyndonnixon there is now a longer list of requirements coming from @michielhildebrand, see the [details](https://lists.iais.fraunhofer.de/sympa/arc/linkedtv-wp2/2014-10/msg00004.html). I think we will make just one update, by end of November.

**Comment by lyndonnixon** [comment]
Note on dimensions in the TVEnricher and TVNewsEnricher responses:

"Here, we would expect WP2 to be able to return dimensions in their service responses, for TKK this is very nicely mapped to the wrapped services which respond (IRAPI -> the "Background" dimension, Europeana -> the "Related Works" dimension, TV2Lucene -> the "Related Chapters" dimension). For RBB we have a time parameter which plays a role (TVEnricher, TVNewsEnricher or TV2Lucene responses dated before the news item -> "Timeline", dated within one week before or after the news item -> "Related") ... @rtroncy: meaning at least you don't need to change how to generate requests, but you do need to add a small logic in the response generation that looks at the news article date."

Can you give us a deadline for this? Nov 28?

**Comment by rtroncy** [comment]
Both the JSON output and the TTL output of TVEnricher will use the proposed method adding an additional motivation for classifying the LinkedTV enrichments
