### ISSUE TITLE
EntityExpansion: add the CSE as a parameter

### ISSUE THREAD

**Issue by rtroncy** [linkedtv/wp2#24]
The [EntityExpansion service description](http://www.linkedtv.eu/wiki/index.php/EntityExpansion) indicates that a default CSE simulating a full complete Google Search is being used by default. A feature enhancement would be to add a user-provided CSE as a parameter to the service.

Recent evaluations show the added-value, see the [spreadsheet data](https://docs.google.com/spreadsheets/d/1_ip2mSnkEqLc1FFXkZZy-qDOBMxqbTL2_t7YsxoZrUg/edit#gid=0) and the [human readable interpretation](http://www.linkedtv.eu/wiki/index.php/WP2#Playground_from_Lyndon)

**Comment by jluisred** [comment]
Both REST API calls in EntityExpansion (representative/relevant) include a new query parameter "cse" which allows to specify the ID of a Google Custom Search Engine to be used during the collection of related documents.

For more details and examples see the [EntityExpansion](http://www.linkedtv.eu/wiki/index.php/EntityExpansion#REST_API_calls) documentation.
