### ISSUE TITLE
TVNewsEnricher: add the CSEs as parameters

### ISSUE THREAD

**Issue by rtroncy** [linkedtv/wp2#25]
The [TVNewsEnricher service description](http://www.linkedtv.eu/wiki/index.php/TVNewsEnricher) indicates that various CSEs are used depending on API calls being made corresponding to enrichment dimensions. This is fixed for the early LinkedNews BBC prototype.

A feature enhancement would be to add user-provided CSEs as parameters to the service in order to replicate the prototype on RBB (German) content.

**Comment by jluisred** [comment]
The four REST API calls in TVNewsEnricher (Opinion/OtherMedia/Timeline/inDepth) include a new query parameter "cse" which allows to specify the ID of the Google Custom Search engine to be used during the collection of related documents.

Example:
curl -X GET "http://linkedtv.eurecom.fr/newsenricher/api/timeline?query=snowden&startdate=20130313&enddate=20140116&cse=CSE_ID&limit=50" --header "Content-Type:application/json" -v

For more details and examples, check the [TVNewsEnricher ](http://www.linkedtv.eu/wiki/index.php/TVNewsEnricher#REST_API_calls) documentation.
