### ISSUE TITLE
TVEnricher: syntactic errors in URLs

### ISSUE THREAD

**Issue by alisarioglu** [linkedtv/wp2#27]
- URLs in identifier separated just with a space character.

Example: 

```
<http://data.linkedtv.eu/entity/94074917-90dd-4f58-98a7-3709d2a6738c>
  a       <http://dbpedia.org/resource/City http://de.dbpedia.org/resource/UIT= http://de.dbpedia.org/resource/Kodex=> , linkedtv:Entity , <http://dbpedia.org/ontology/Place> ;
  rdfs:label "Zurich"^^xsd:string ;
  dc:source "thd" ;
  owl:sameAs <http://dbpedia.org/resource/Zurich> .
```
- Invalid characters:
  
  SP029: TURTLE RDF loader, line 25: Invalid characters in angle-bracketed name; this error can be suppressed by parser flags at &lt;http://images.textielmuseum.nl:85/wwwopac.ashx?command=getcontent&amp;server=images&amp;value=TMTploeg\TMT001300997-026.jpg&amp;width=230&amp;height=230&amp;scalemode=fill&amp;fillmode=center&gt; processed pending to here.

**Comment by jluisred** [comment]
TVEnricher has been modified to rely on the JSON annotations coming from IRAPI instead of the former string based attribute in order to get the THD's entities, so TVEnricher is now free of unexpected parsing errors.
