### ISSUE TITLE
TVEnricher: some indexing issues with (probably) MediaCollector

### ISSUE THREAD

**Issue by lyndonnixon** [linkedtv/wp2#30]
From our experiment for EUScreenXL:

TVEnricher [1] does get a lot of wikimedia images for videophone. It also returns one video from openimages.eu which has the same label as ours but a different URL (http://openimages.eu/media/22071/Rijkstelegraaf_bestaat_honderd_jaar). A mistake in the indexing process?

Even better, TVEnricher with "beeldtelefoon" [2] returns 5 videos (including our own one). Sadly the response types all the OGG audio and OGV video links as 'photo' so it looks like we can't sort the responses better currently.

[1] http://linkedtv.eurecom.fr/tvenricher/api/entity/enrichment/SV?q=videophone
[2] http://linkedtv.eurecom.fr/tvenricher/api/entity/enrichment/SV?q=beeldtelefoon

**Comment by rtroncy** [comment]
This was actually related to IRAPI rather than MediaCollector and has been fixed
