### ISSUE TITLE
UEP: duplicate results

### ISSUE THREAD

**Issue by lyndonnixon** [linkedtv/wp2#4]
Images doubled in results, from both museummartena.nl and www.museummartena.nl

**Comment by rtroncy** [comment]
@kliegr Can you clarify when this issue will be resolved: is it part of the 25/08 new release of IRAPI or is it part of a later mid-September release?

**Comment by kliegr** [comment]
This will not be part of the 25/08 release. The will be fixed by performing host normalization in the crawling phase.

**Comment by rtroncy** [comment]
What is the ETA then?

**Comment by kliegr** [comment]
The fix will be deployed on ~ 15/09. Depending on the exact solution, it will take additional time to propagate.

**Comment by rtroncy** [comment]
@kliegr Can you please let us know when the re-indexing is complete and when we can close this issue?

**Comment by cervebar** [comment]
info: The cleanup of irapi webpage index has finished. Now we are performing the cleanup of the media indexes. Given the large number of objects indexed and the corresponding volume of HTTP request, this is estimated to take 3-6 days. Once the cleanup has finished, this should resolve github issues #4, #11.

**Comment by rtroncy** [comment]
Following my comments on issue #11 can we close this issue as well? Can you please provide evidences that we don't have anymore duplicate results?
