### ISSUE TITLE
EURECOM MediaCollector: tighten up YouTube responses

### ISSUE THREAD

**Issue by lyndonnixon** [linkedtv/wp2#6]
e.g. 'Hessel Martena' gets YouTube videos with just "Hessel" in the description besides 2 relevant video matches which have Hessel van Martena in their description. 

With actors/presenters one could combine searches with TV/film appearances, e.g.
https://www.youtube.com/results?search_query=intitle%3A%22Opsporing+Verzocht%22+%22nelleke+van+der+krogt%22

Top 2 matches are directly relevant, not sure how to get rid of the other 5 without postprocessing since Nelleke doesnt even appear in the descriptions.

**Comment by rtroncy** [comment]
A priori, one could get the desired effect with the new  'on-demand' TVEnricher functionality by issue-ing the right constrained query
