### ISSUE TITLE
New APIs and content sources for LinkedTV

### ISSUE THREAD

**Issue by lyndonnixon** [linkedtv/wp2#7]
Identified as interesting for LinkedTV enrichment:

Foursquare Venues: provide address, telephone, user tips, photos
Flickr: geolocated photo search
Instagram: geolocated photo search
Google or Open Street Map:  map image of place or location
Rijksstudio  (art objects in a Pinterest-like site)

**Comment by rtroncy** [comment]
Unclear feature request: Flickr, Instagram, etc. are already part of MediaCollector/TVEnricher

Foursquare venues are very noisy in general, with a lot of duplicates. There was no such a request from the content provider which do not seem to like SocialMedia in general.

Unclear feature request regarding maps ... we have already geo-coordinates and a second screen app can already display a map centered around a POI, this is not something we will materialize in RDF in the enrichments.

Rijkstudio: is this new source on some white list?
