### ISSUE TITLE
EURECOM - TVEnricher: support JSON response, containing enrichment results

### ISSUE THREAD

**Issue by jblom** [linkedtv/wp2#9]
The JSON response should be in the format specified in: 

https://docs.google.com/a/beeldengeluid.nl/document/d/10BLFESGbqJr_AOxjF0eTjOEGSvFu4qJNm2nrX2lS3l4/edit#heading=h.14w9r33san65

**Comment by rtroncy** [comment]
Done, see http://www.linkedtv.eu/wiki/index.php/Tvenricher for the documentation
